config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, only: [:show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  has_many_attached :photos
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_many_attached :photos
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, photos: [])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col">
      <%= image_tag("https://ae01.alicdn.com/kf/H4f3caed560ec421d82d2971ae57082288/10-Sheets-Retro-Paper-Texture-Standable-Movie-Themes-Film-Bookmarks-for-Reading-Pages-DIY-Book-Accessories.jpg_Q90.jpg_.webp", width: 600) %>
    </div>
    <div class="col py-5">
      <div class="d-flex justify-content-center my-4">
        <h1 class="letter d-flex justify-content-center">Add a new bookmark</h1>
      </div>
      <div class="letter d-flex justify-content-center my-3">
        <%= simple_form_for [ @list, @bookmark ] do |f| %>
          <%= f.input :comment %>
          <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          <%= f.association :movie %>
          <div class="d-flex justify-content-center"><%= f.submit "Save", class: "btn btn-warning my-3" %></div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Watch List</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <body class="back">
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <div class="container-fluid">
        <%= link_to root_path, class: "navbar-brand" do %>
          <div class= "enterprise">
            <%= image_tag("https://thumbs.dreamstime.com/b/popcorn-entradas-y-filmaciones-sobre-la-mesa-con-fondo-negro-tiras-de-cine-pelota-en-gris-contra-163110029.jpg", class: "logo") %>
          </div>
        <% end %>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
            <li class="nav-item dropdown">
              <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/dinorahskidelsky"/>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Add a new list", new_list_path, class: "dropdown-item" %>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://estaticos.muyinteresante.es/uploads/images/gallery/58402b605cafe8877e8b456c/peliculas.jpg);">
  <div class="container">
    <h1 class="d-flex justify-content-end">SAVE ANY KIND OF MOVIES</h1>
  </div>
</div>
<h2 class="d-flex justify-content-center text-light my-5">LISTS</h2>
<div class= container>
  <div class="cards">
    <% @lists.each do |list| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://i.pinimg.com/736x/59/d8/72/59d8726a7542bb71f75c92e4da6dc819.jpg)">
        <p><%= link_to list.name, list_path(list), {:style=>'color:#000000;', :class => "css_class"} %></p>
      </div>
    <% end %>
  </div>
</div>
<div class="footer mt-5">
  <div class="footer-links">
    <%# <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a> %>
  </div>
  <div class="footer-copyright">
    This page was made whit ♥️ by <a class="letter" href="https://github.com/DinorahSkidelsky">Dinorah Skidelsky</a>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col">
      <%= image_tag("https://c1.wallpaperflare.com/preview/892/839/660/ciack-direction-director-film.jpg", width: 750) %>
    </div>
    <div class="col py-5">
      <div class="d-flex justify-content-center my-4">
        <h1 class="letter d-flex justify-content-center">New List</h1>
      </div>
      <div class="letter d-flex justify-content-center my-3">
        <%= simple_form_for(@list) do |f| %>
          <%= f.input :name %>
          <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          <div class="d-flex justify-content-center"><%= f.submit "Save", class: "btn btn-warning my-3" %></div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="banner">
   <% @list.photos.each do |photo| %>
        <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
      <% end %>
</div>
<h2 class="d-flex justify-content-center text-light my-5"><%= @list.name %></h2>
<div class="container">
  <div class="cards">
    <ul class="list-group">
      <% @list.movies.each do |movie| %>
        <div class="list-group-item">
          <li class="d-flex justify-content-center"><%= movie.title %></li>
          <li class="d-flex justify-content-center"><%= movie.overview %></li>
          <li class="d-flex justify-content-center"><%= movie.poster_url %></li>
          <li class="d-flex justify-content-center"><%= movie.rating %></li>
        </div>
      <% end %>
    </ul>
  </div>
  <div class="container">
  <div class="cards">
    <ul class="list-group">


      <% @list.bookmarks.each do |bookmark| %>
        <li class="list-group-item d-flex justify-content-center">
          <%= bookmark.comment %>
          <%= bookmark.photos.each do |photo| %>
              <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
          <% end %>

          <div class="d-flex justify-content-center">
            <%= link_to "Delete",
              bookmark_path(bookmark),
              method: :delete,
              data: { confirm: "Are you sure?" } %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
  </div>
  <p class="d-flex justify-content-end"><%= link_to 'Add a new bookmark', new_list_bookmark_path(@list) , class: "btn btn-warning"%></p>
</div>